---
- hosts: cde
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false

  tasks:
  - lineinfile:
      path: /etc/sysconfig/init
      regexp: '^SINGLE=/sbin/sushell'
      line: 'SINGLE=/sbin/sulogin'

