- hosts: useradd
  become_user: root
  become: yes
  gather_facts: false
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "zaq1!QAZ")'
    user_password: $6$C.7BtU4LW7Uw1Rjj$IHEDgsCgEERLHVMSDt3.8VeFVSDkLOQX/3Nrz2udqH/S4Wv2hsQ6miO5sKNhSNXgTAbf0G3s2l3OV/HouQJq50
    root_password: $6$OjFWgXLohd8O6P/l$fS5fcUqzeZnUuuj7lZOVwFQV04mTbXtaP.mb95lpTbXdl6JmDnlixwEHIgf/ycMZqao9TNoqVwxqBGzqr4cll1
    user_name: mathan.chanemougamourty
  tasks:
  - name: Create new user
    user: 
     name: '{{ user_name }}'
     password: '{{user_password}}'
     shell: /bin/bash
     state: present
     remove: no
    tags: Create_user

 # - name: root password change
 #   user: name=root update_password=always password= "{{ root_password }}"
 #   tags: update_root_pass

  - name: Adding user to sudo
    lineinfile:
       path: /etc/sudoers
       insertafter: '^cloudsvc'
       line: '{{ user_name }}  ALL=(ALL)       NOPASSWD: ALL'
    tags: sudo_user
